### ISSUE TITLE
some Improvements/ideas:

### ISSUE THREAD

**Issue by leasoncre** [TVPT/VoxelGunsmith#11]
1. support block logging ie: coreprotect (might be able to just hook into worldedit to pass block data?) -or though another plugin to pass to a specific/any logging plugin.
2. either natively or though another plugin: asynchronous black changes. (probably a long term goal thing if implemented. since sniper doesn't change to many blocks at once, it may not be needed for the majority of servers out there)
3. config option to set maximum brush size. (if there isn't already a limit. if it can be set to a large enough size, someone could potentially crash a server with too many block changes.)
4. if it doesn't already. be able to assign brushes to other items.

other thoughs:
/vr is the root command for voterullete plugin and voxel overides it. while voterulette has a config option to change this, i'd prefer not too.
a few of the other short-hand commands do similarly with other plugins. but not personally concerned about those.

**Comment by Deamon5550** [comment]
1. Its planned to provide the hooks for this if someone else wanted to hook in to it
2. already implemented
3. 2 kind of solves this but sure
4. thats the brush tool functionality from the old version not yet ported though

any command conflicts can be handled with the commands.yml configuration that bukkit provides

I'm going to close this because there isn't anything actionable here that isn't already on the roadmap
